// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsldC6bZ2zpwZBDNheTCj9itakbuDhS_g',
    appId: '1:189199223338:android:f9271075962beb307ad153',
    messagingSenderId: '189199223338',
    projectId: 'gold-dev-a8477',
    storageBucket: 'gold-dev-a8477.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwDHEnMcb9RfQTWzJJjrgpMRC6ug89ic4',
    appId: '1:189199223338:ios:1a93e11d26079e857ad153',
    messagingSenderId: '189199223338',
    projectId: 'gold-dev-a8477',
    storageBucket: 'gold-dev-a8477.firebasestorage.app',
    iosBundleId: 'com.saudi.goldprice.dev',
  );

}