// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_delivery.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQPT-3nUJyaip-bYLP-tBl9cPUE9EKdXY',
    appId: '1:694252360716:android:37f71cf7a9c2990b3e0a29',
    messagingSenderId: '694252360716',
    projectId: 'shiphub-dd08d',
    storageBucket: 'shiphub-dd08d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANN5NHA7ZsPYgmN0ramltZVDSflP0BWdU',
    appId: '1:694252360716:ios:e5a798ae17baa5ff3e0a29',
    messagingSenderId: '694252360716',
    projectId: 'shiphub-dd08d',
    storageBucket: 'shiphub-dd08d.firebasestorage.app',
    iosBundleId: 'com.shiphub.delivery',
  );

}